###
### At minimum you must configure METRICS_URL, CIRCUITPY_WIFI_SSID, and
### CIRCUITPY_WIFI_PASSWORD or else this won't do anything. Consult the
### README for more information on these settings and settings.py
###

# URL to retrieve Uptime Kuma Prometheus metrics. Should end in /metrics
METRICS_URL = "http://something/metrics"

# API token for Uptime Kuma. Needed if authentication is enabled.
# API_TOKEN = ""

# WiFi information.
CIRCUITPY_WIFI_SSID = ""
CIRCUITPY_WIFI_PASSWORD = ""

# CircuitPythong Web workflow information.
# CIRCUITPY_WEB_API_PASSWORD = ""
# CIRCUITPY_WEB_API_PORT = 80
